### ISSUE TITLE
Docs are incredibly out of date

### ISSUE THREAD

**Issue by Chrono-byte** [pizzafox/dice-docs#61]
The commando commands group is still present in the docs along with many other currently not present commands. This may cause confusion with some users and cause them to raise an issue in the help channel in the Discord server.

**Comment by jonahsnider** [comment]
A new generation system is WIP and should be released within 6 hours.

**Comment by jonahsnider** [comment]
I got really busy in the last few days and haven't been able to push the release. I've made a fair deal of progress, the new generation code is written, I just need to finalize the connection between the docs repo and the generator.

**Comment by jonahsnider** [comment]
New docs are written, just need to get Netlify to properly build it with the custom script.

**Comment by jonahsnider** [comment]
Netlify works, but GitHub Actions doesn't. That doesn't matter though. The new docs are getting published. Note that you need to rerun Netlify in order to regenerate the docs when commands get updated in the bot repo. In the future this process might get automated, depends on how the documentation system works.
